### ISSUE TITLE
Web component needs to be updated for ES6 compatbility

### ISSUE THREAD

**Issue by sirloon** [biothings/biothings.species#1] opened 2019-02-13 16:03 UTC
MyTaxonomy is being migrated to ES6 and latest biothings code base. Currently, running it says: 

```
AttributeError: No setting named 'APP_LIST' was found, check configuration module.
```

showing code is outdated (iirc) + it may need update in ES queries performed against version 6.1

**Comment by namespacestd0** [comment] 2019-03-22 17:24
The cause is "requirements_web.txt" as of commit 25c53d98e8110a4fa7d01ab332e9a32a0809c3a3 specified an out-dated biothings.api dependency version. It is observed to be fixed by commit 8dc138c425f5df58ff4ec53cb59e11402f72ae8e.

**Closed by namespacestd0** 2019-03-22 17:24 UTC
Labels: enhancement
